apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: rkalluru/d52-user:TAG
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: redis-master
            - name: MONGO_URL
              value: "mongodb://mongodb:27017/users"
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
