apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: rkalluru/d52-payment:TAG
          ports:
            - containerPort: 8080
          env:
            - name: AMQP_HOST
              value: rabbitmq
            - name: AMQP_USER
              value: roboshop
            - name: AMQP_PASS
              value: roboshop123
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  type: ClusterIP
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
