pipeline {
  agent any

  environment {
    AWS = credentials('AWS')
  }

  parameters {
    string(name: 'component', defaultValue: '', description: 'Which Component of RoboShop Application')
  }

  stages {

    stage('Make AMI') {
      steps {
        sh '''
          export TF_VAR_component=${component}
          export AWS_ACCESS_KEY_ID=${AWS_USR}
          export AWS_SECRET_ACCESS_KEY=${AWS_PSW}
          export TF_VAR_ARTIFACT_VERSION=${BUILD_NUMBER}
          make dev-apply
          terraform state rm aws_ami_from_instance.ami 
          make dev-destroy
        '''
      }
    }
  }

}